// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task-service/proto/task.proto

package go_micro_srv_task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId               uint64               `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Task) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type CreateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{1}
}
func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(dst, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{2}
}
func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(dst, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetTaskRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{3}
}
func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (dst *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(dst, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteTaskRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{4}
}
func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(dst, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListTasksRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{5}
}
func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (dst *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(dst, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

func (m *ListTasksRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListTasksResponse struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{6}
}
func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (dst *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(dst, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type TaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskResponse) Reset()         { *m = TaskResponse{} }
func (m *TaskResponse) String() string { return proto.CompactTextString(m) }
func (*TaskResponse) ProtoMessage()    {}
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_dd00d82b88a4e56e, []int{7}
}
func (m *TaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskResponse.Unmarshal(m, b)
}
func (m *TaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskResponse.Marshal(b, m, deterministic)
}
func (dst *TaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskResponse.Merge(dst, src)
}
func (m *TaskResponse) XXX_Size() int {
	return xxx_messageInfo_TaskResponse.Size(m)
}
func (m *TaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskResponse proto.InternalMessageInfo

func (m *TaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "go.micro.srv.task.Task")
	proto.RegisterType((*CreateTaskRequest)(nil), "go.micro.srv.task.CreateTaskRequest")
	proto.RegisterType((*UpdateTaskRequest)(nil), "go.micro.srv.task.UpdateTaskRequest")
	proto.RegisterType((*GetTaskRequest)(nil), "go.micro.srv.task.GetTaskRequest")
	proto.RegisterType((*DeleteTaskRequest)(nil), "go.micro.srv.task.DeleteTaskRequest")
	proto.RegisterType((*ListTasksRequest)(nil), "go.micro.srv.task.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "go.micro.srv.task.ListTasksResponse")
	proto.RegisterType((*TaskResponse)(nil), "go.micro.srv.task.TaskResponse")
}

func init() { proto.RegisterFile("task-service/proto/task.proto", fileDescriptor_task_dd00d82b88a4e56e) }

var fileDescriptor_task_dd00d82b88a4e56e = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0xad, 0x1a, 0x15, 0x6f, 0x8a, 0x34, 0xf3, 0xa0, 0x21, 0xa5, 0x68, 0xa3, 0x0f, 0xa5, 0xc5,
	0x11, 0xec, 0x63, 0x5f, 0x4a, 0x3f, 0x28, 0x05, 0xa1, 0x90, 0x2a, 0xec, 0xdb, 0x12, 0xcd, 0x28,
	0xc3, 0x1a, 0x27, 0x9b, 0x19, 0x85, 0xfd, 0x21, 0xfb, 0x4f, 0xf6, 0x07, 0xee, 0xcc, 0x24, 0x59,
	0x35, 0xc9, 0x8a, 0xcb, 0xbe, 0xdd, 0x8f, 0x73, 0xcf, 0x9c, 0x99, 0x73, 0x07, 0x3e, 0x08, 0x9f,
	0xdf, 0x8c, 0x38, 0x89, 0xf7, 0x74, 0x49, 0xc6, 0x51, 0xcc, 0x04, 0x1b, 0xab, 0x12, 0xd6, 0x21,
	0xb2, 0xd6, 0x0c, 0x87, 0x74, 0x19, 0x33, 0xcc, 0xe3, 0x3d, 0x56, 0x0d, 0xa7, 0xb7, 0x66, 0x6c,
	0xbd, 0x49, 0xb1, 0x8b, 0xdd, 0x6a, 0x2c, 0x68, 0x48, 0xb8, 0xf0, 0xc3, 0x28, 0x99, 0x71, 0xde,
	0xe7, 0x01, 0x24, 0x8c, 0xc4, 0x5d, 0xd2, 0x74, 0xef, 0x2b, 0x60, 0xcc, 0x24, 0x0d, 0x6a, 0x43,
	0x95, 0x06, 0x76, 0xa5, 0x5f, 0xf9, 0x64, 0x78, 0x32, 0x42, 0x08, 0x8c, 0xad, 0x1f, 0x12, 0xbb,
	0x2a, 0x2b, 0x2d, 0x4f, 0xc7, 0xa8, 0x0f, 0x66, 0x40, 0xf8, 0x32, 0xa6, 0x91, 0xa0, 0x6c, 0x6b,
	0xd7, 0x74, 0xeb, 0xb8, 0x84, 0xba, 0xd0, 0xdc, 0x49, 0xf1, 0xd7, 0x92, 0xca, 0xd0, 0x54, 0x0d,
	0x95, 0xfe, 0x0d, 0x10, 0x06, 0x23, 0xf0, 0x05, 0xb1, 0xeb, 0xb2, 0x6a, 0x4e, 0x1c, 0x9c, 0x68,
	0xc2, 0x99, 0x26, 0x3c, 0xcb, 0x44, 0x7b, 0x1a, 0xe7, 0x7e, 0x07, 0xeb, 0x67, 0x4c, 0x64, 0xa4,
	0xc4, 0x79, 0xe4, 0x76, 0x27, 0xbb, 0xe8, 0x0b, 0x18, 0xea, 0xca, 0x5a, 0xa5, 0x39, 0xe9, 0xe2,
	0xc2, 0x63, 0x60, 0x8d, 0xd6, 0x20, 0xc5, 0x30, 0x8f, 0x82, 0xd7, 0x30, 0xf4, 0xa1, 0xfd, 0x87,
	0x88, 0xe3, 0xf1, 0xdc, 0x23, 0xb9, 0x03, 0xb0, 0x7e, 0x91, 0x0d, 0x39, 0x3d, 0x23, 0x0f, 0xfa,
	0x0c, 0xef, 0xa6, 0x94, 0x6b, 0x1e, 0x9e, 0x61, 0x3a, 0xd0, 0x58, 0xd1, 0x8d, 0x20, 0xb1, 0xc6,
	0xb5, 0xbc, 0x34, 0x73, 0x7f, 0x80, 0x75, 0x84, 0xe5, 0x11, 0xdb, 0x72, 0x82, 0x46, 0x50, 0xd7,
	0x05, 0x89, 0xad, 0x9d, 0x53, 0x9d, 0xa0, 0xdc, 0x6f, 0xf0, 0x36, 0x91, 0x93, 0x8e, 0xbf, 0xe4,
	0xce, 0x93, 0x87, 0x1a, 0x98, 0x2a, 0xfd, 0x9f, 0x6c, 0x20, 0x9a, 0x03, 0x1c, 0x7c, 0x40, 0xc3,
	0x92, 0xe1, 0x82, 0x4d, 0x4e, 0xef, 0xb9, 0x23, 0x52, 0x45, 0xee, 0x1b, 0x45, 0x7b, 0x30, 0xa7,
	0x94, 0xb6, 0xe0, 0xdd, 0x25, 0xb4, 0x53, 0x80, 0x83, 0x1f, 0xa5, 0xb4, 0x05, 0xbb, 0x9c, 0x4e,
	0x61, 0x17, 0x7f, 0xab, 0xff, 0x21, 0xd9, 0xfe, 0x41, 0x33, 0xf5, 0x1f, 0x7d, 0x2c, 0xa1, 0x3a,
	0xdd, 0x8d, 0x4b, 0xe4, 0x5d, 0x41, 0xeb, 0xc9, 0x5d, 0x34, 0x28, 0xc1, 0xe7, 0xf7, 0xc4, 0x19,
	0x9e, 0x07, 0x65, 0xcc, 0x8b, 0x86, 0x16, 0xff, 0xf5, 0x31, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x58,
	0xac, 0x2a, 0x3f, 0x04, 0x00, 0x00,
}
