version: '3.1'

services:

  task-cli:
    image: task-cli:latest
    #build: ./task-cli
    environment:
      MICRO_REGISTRY: "mdns"
    container_name: task-cli  

  user-cli:
    image: user-cli:latest
    #build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"
    container_name: user-cli  

  task-service:
    image: task-service:latest
    #build: ./task-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    container_name: task-service

  user-service:
    image: user-service:latest
    #build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5555"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    container_name: user-service
    depends_on:
      - database

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5555:5555